part1: part1.cpp
	@g++ part1.cpp
	@./a.out input.ppm output_part1.ppm
	@echo "Done. Check output_part1.ppm for output."
part2_1a: part2_1a.cpp
	@g++ part2_1a.cpp -lpthread
	@./a.out input.ppm output_part2_1a.ppm
	@echo "Done. Check output_part2_1a.ppm for output."
part2_1b: part2_1b.cpp
	@g++ part2_1b.cpp -lpthread
	@./a.out input.ppm output_part2_1b.ppm
	@echo "Done. Check output_part2_1b.ppm for output."
part2_2: part2_2.cpp
	@g++ part2_2.cpp -lpthread
	@./a.out input.ppm output_part2_2.ppm
	@echo "Done. Check output_part2_2.ppm for output."
part2_3: part2_3.cpp
	@g++ part2_3.cpp -lpthread
	@./a.out input.ppm output_part2_3.ppm
	@echo "Done. Check output_part2_3.ppm for output."